---
title: Homelab
theme: dark
color: slate
layout:
  Infrastructure:
    style: row
    columns: 4
  Productivity:
    style: row
    columns: 4
  Photos & Media:
    style: row
    columns: 4
  Downloads:
    style: row
    columns: 4
  Misc:
    style: row
    columns: 3
