---
title: Homelab
theme: dark
color: slate
background: "#282828"
layout:
  Infrastructure:
    style: row
    columns: 4
  Productivity:
    style: row
    columns: 4
  Photos & Media:
    style: row
    columns: 4
  Downloads:
    style: row
    columns: 3
  Storage:
    style: row
    columns: 3
