- glances:
    url: http://10.0.0.10:61208
    cpu: true
    mem: true
    disk: /
    diskUnits: bytes
    label: theseus

- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: short
      hourCycle: h23
